import "unknwn.idl";

[uuid(fda89968-0885-4949-9b6d-805186f11fb9), version(1.0), helpstring("DemoAudioEngine")]
library DemoAudioEngine
{
    [object, uuid(da981f98-3749-4af0-8813-f7cdd59e1690)]
    interface DemoAudioEngineCallbacksIntf : IUnknown
    {
        HRESULT filePlaybackFinished();
    };

    [object, uuid(c1a01b40-ede0-44ff-93f8-b59396ff678d)]
    interface DemoAudioEngineIntf : IUnknown
    {
        HRESULT play([in, string] wchar_t* url);
        HRESULT stop();

        HRESULT pause();
        HRESULT resume();

        HRESULT setRoomSize([in] float roomSize);
        HRESULT setLowpassCutoff([in] float cutoff);

        HRESULT setCallback([in] DemoAudioEngineCallbacksIntf callbackObj);

        HRESULT addWaveformComponentToHWND([in] void* host, [out, retval] void* client);
        HRESULT removeWaveformComponentFromHWND();
    };
};
